services:
  app:
    #build: .
    image: prestabooks:1.0.1
    ports:
      - 8080:3000
    environment:
      - APP_DATABASE_HOST=postgres
      - APP_DATABASE_PORT=5432
      - APP_DATABASE_USERNAME=postgres
      - APP_DATABASE_PASSWORD=123456
    links:
      - postgres:postgres
  
  postgres:
    image: postgres:13.4-alpine
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=prestabooks_db

  pgadmin:
    image: dpage/pgadmin4:5.6
    ports:
      - 80:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=darpa@darpa.com
      - PGADMIN_DEFAULT_PASSWORD=123456789
    links:
      - postgres:postgres